// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxawsiot.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxawsiot.impl.IoTConnector;

/**
 * Get current state for thing
 * 
 */
public class GetThingState extends CustomJavaAction<java.lang.String>
{
	private java.lang.String AwsAccessKeyId;
	private java.lang.String AwsSecretAccessKey;
	private java.lang.String AwsRegion;
	private java.lang.String AwsEndpoint;
	private java.lang.String ThingName;

	public GetThingState(IContext context, java.lang.String AwsAccessKeyId, java.lang.String AwsSecretAccessKey, java.lang.String AwsRegion, java.lang.String AwsEndpoint, java.lang.String ThingName)
	{
		super(context);
		this.AwsAccessKeyId = AwsAccessKeyId;
		this.AwsSecretAccessKey = AwsSecretAccessKey;
		this.AwsRegion = AwsRegion;
		this.AwsEndpoint = AwsEndpoint;
		this.ThingName = ThingName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		IoTConnector connector = new IoTConnector();
		connector.setLogger(Core.getLogger(DescribeThing.class.getName()));
		connector.setCredentials(this.AwsAccessKeyId, this.AwsSecretAccessKey);
		connector.setRegion(this.AwsRegion);
		connector.setEndpoint(this.AwsEndpoint);
		String result = connector.getThingShadow(this.ThingName);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetThingState";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
