// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxawsiot.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxawsiot.impl.IoTConnector;

/**
 * Get current state for thing
 * 
 */
public class GetThingState extends CustomJavaAction<java.lang.String>
{
	private java.lang.String AwsAccessKeyId;
	private java.lang.String AwsSecretAccessKey;
	private java.lang.String Region;
	private java.lang.String ThingName;
	private java.lang.String Endpoint;

	public GetThingState(IContext context, java.lang.String AwsAccessKeyId, java.lang.String AwsSecretAccessKey, java.lang.String Region, java.lang.String ThingName, java.lang.String Endpoint)
	{
		super(context);
		this.AwsAccessKeyId = AwsAccessKeyId;
		this.AwsSecretAccessKey = AwsSecretAccessKey;
		this.Region = Region;
		this.ThingName = ThingName;
		this.Endpoint = Endpoint;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		//throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		IoTConnector connector = new IoTConnector();
		connector.setLogger(Core.getLogger(DescribeThing.class.getName()));
		connector.setCredentials(this.AwsAccessKeyId, this.AwsSecretAccessKey);
		connector.setRegion(this.Region);
		connector.setEndpoint(this.Endpoint);
		String result = connector.getThingShadow(this.ThingName);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetThingState";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
