// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxawsiot.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxawsiot.impl.IoTConnector;

/**
 * List all registered AWS IoT things available to specified AWS account.
 * 
 * http://docs.aws.amazon.com/iot/latest/apireference/API_ListThings.html
 * http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/iot/model/ListThingsRequest.html
 * http://docs.amazonaws.cn/AWSJavaSDK/latest/javadoc/com/amazonaws/services/iot/AWSIotClient.html
 */
public class ListThings extends CustomJavaAction<String>
{
	private String AwsAccessKeyId;
	private String AwsSecretAccessKey;
	private String Region;
	private String AttributeName;
	private String AttributeValue;

	public ListThings(IContext context, String AwsAccessKeyId, String AwsSecretAccessKey, String Region, String AttributeName, String AttributeValue)
	{
		super(context);
		this.AwsAccessKeyId = AwsAccessKeyId;
		this.AwsSecretAccessKey = AwsSecretAccessKey;
		this.Region = Region;
		this.AttributeName = AttributeName;
		this.AttributeValue = AttributeValue;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
        //throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
        IoTConnector connector = new IoTConnector();
        connector.setLogger(Core.getLogger(ListThings.class.getName()));
        connector.setCredentials(this.AwsAccessKeyId, this.AwsSecretAccessKey);
		connector.setRegion(this.Region);
        String jsonResponse = connector.listThingsRest(this.AttributeName,this.AttributeValue);
        return jsonResponse;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ListThings";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
