// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxawsiot.actions;

import com.mashape.unirest.http.JsonNode;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import mxawsiot.impl.IoTConnector;
import mxawsiot.proxies.IotThing;

/**
 * List all registered AWS IoT things available to specified AWS account.
 * 
 * http://docs.aws.amazon.com/iot/latest/apireference/API_ListThings.html
 * http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/iot/model/ListThingsRequest.html
 * http://docs.amazonaws.cn/AWSJavaSDK/latest/javadoc/com/amazonaws/services/iot/AWSIotClient.html
 */
public class ListThingsToEntities extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String AwsAccessKeyId;
	private java.lang.String AwsSecretAccessKey;
	private java.lang.String AwsRegion;
	private java.lang.String AttributeName;
	private java.lang.String AttributeValue;
	private IMendixObject __ResultFirstEntity;
	private mxawsiot.proxies.IotThing ResultFirstEntity;
	private java.util.List<IMendixObject> __ResultList;
	private java.util.List<mxawsiot.proxies.IotThing> ResultList;

	public ListThingsToEntities(IContext context, java.lang.String AwsAccessKeyId, java.lang.String AwsSecretAccessKey, java.lang.String AwsRegion, java.lang.String AttributeName, java.lang.String AttributeValue, IMendixObject ResultFirstEntity, java.util.List<IMendixObject> ResultList)
	{
		super(context);
		this.AwsAccessKeyId = AwsAccessKeyId;
		this.AwsSecretAccessKey = AwsSecretAccessKey;
		this.AwsRegion = AwsRegion;
		this.AttributeName = AttributeName;
		this.AttributeValue = AttributeValue;
		this.__ResultFirstEntity = ResultFirstEntity;
		this.__ResultList = ResultList;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.ResultFirstEntity = __ResultFirstEntity == null ? null : mxawsiot.proxies.IotThing.initialize(getContext(), __ResultFirstEntity);

		this.ResultList = new java.util.ArrayList<mxawsiot.proxies.IotThing>();
		if (__ResultList != null)
			for (IMendixObject __ResultListElement : __ResultList)
				this.ResultList.add(mxawsiot.proxies.IotThing.initialize(getContext(), __ResultListElement));

		// BEGIN USER CODE
        IoTConnector connector = new IoTConnector();
        connector.setLogger(Core.getLogger(ListThingsToEntities.class.getName()));
        connector.setCredentials(this.AwsAccessKeyId, this.AwsSecretAccessKey);
		connector.setRegion(this.AwsRegion);
		JsonNode jsonResponse = connector.listThingsRestJson();
        org.json.JSONArray things = jsonResponse.getObject().getJSONArray("things");
        for (int i = 0; i < things.length(); i++) {
            org.json.JSONObject thing = things.getJSONObject(i);
            mxawsiot.proxies.IotThing t = new IotThing(this.getContext());
            t.setName(thing.getString("thingName"));
            this.__ResultList.add(t.getMendixObject());
        }
        //return jsonResponse;
        //for (AnyObject e : this.ResultList)
        //	this.__ResultList.add(e.getMendixObject());
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ListThingsToEntities";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
