// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxawsiot.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxawsiot.impl.MqttConnector;

public class SubscribeToTopic extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String BrokerHost;
	private java.lang.Long BrokerPort;
	private java.lang.Long Timeout;
	private java.lang.String TopicName;
	private java.lang.String OnMessageMicroflow;
	private java.lang.String CA;
	private java.lang.String ClientCertificate;
	private java.lang.String ClientKey;
	private java.lang.String CertificatePassword;

	public SubscribeToTopic(IContext context, java.lang.String BrokerHost, java.lang.Long BrokerPort, java.lang.Long Timeout, java.lang.String TopicName, java.lang.String OnMessageMicroflow, java.lang.String CA, java.lang.String ClientCertificate, java.lang.String ClientKey, java.lang.String CertificatePassword)
	{
		super(context);
		this.BrokerHost = BrokerHost;
		this.BrokerPort = BrokerPort;
		this.Timeout = Timeout;
		this.TopicName = TopicName;
		this.OnMessageMicroflow = OnMessageMicroflow;
		this.CA = CA;
		this.ClientCertificate = ClientCertificate;
		this.ClientKey = ClientKey;
		this.CertificatePassword = CertificatePassword;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        MqttConnector connector = new MqttConnector();
        ILogNode logger = Core.getLogger(SubscribeToTopic.class.getName());
        logger.info("executeAction: topic: " + this.TopicName);
        connector.subscribe(
                this.BrokerHost
                , this.BrokerPort
                , this.TopicName
                , this.OnMessageMicroflow
                , this.CA
                , this.ClientCertificate
                , this.ClientKey
                , this.CertificatePassword
        );
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SubscribeToTopic";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
