// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxawsiot.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxawsiot.impl.MqttConnector;

public class SubscribeToTopic extends CustomJavaAction<Boolean>
{
	private String BrokerHost;
	private Long BrokerPort;
	private Long Timeout;
	private String TopicName;
	private String OnMessageMicroflow;
	private String CA;
	private String ClientCertificate;
	private String ClientKey;
	private String CertificatePassword;

	public SubscribeToTopic(IContext context, String BrokerHost, Long BrokerPort, Long Timeout, String TopicName, String OnMessageMicroflow, String CA, String ClientCertificate, String ClientKey, String CertificatePassword)
	{
		super(context);
		this.BrokerHost = BrokerHost;
		this.BrokerPort = BrokerPort;
		this.Timeout = Timeout;
		this.TopicName = TopicName;
		this.OnMessageMicroflow = OnMessageMicroflow;
		this.CA = CA;
		this.ClientCertificate = ClientCertificate;
		this.ClientKey = ClientKey;
		this.CertificatePassword = CertificatePassword;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        MqttConnector connector = new MqttConnector();
        ILogNode logger = Core.getLogger(SubscribeToTopic.class.getName());
        logger.info("executeAction: topic: " + this.TopicName);
        connector.subscribe(
                this.BrokerHost
                , this.BrokerPort
                , this.TopicName
                , this.OnMessageMicroflow
                , this.CA
                , this.ClientCertificate
                , this.ClientKey
                , this.CertificatePassword
        );
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SubscribeToTopic";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
