// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxawsiot.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxawsiot.impl.IoTConnector;

/**
 * Set current state for thing
 * 
 */
public class UpdateThingState extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String AwsAccessKeyId;
	private java.lang.String AwsSecretAccessKey;
	private java.lang.String AwsEndpoint;
	private java.lang.String AwsRegion;
	private java.lang.String ThingName;
	private java.lang.String DesiredThingStatus;

	public UpdateThingState(IContext context, java.lang.String AwsAccessKeyId, java.lang.String AwsSecretAccessKey, java.lang.String AwsEndpoint, java.lang.String AwsRegion, java.lang.String ThingName, java.lang.String DesiredThingStatus)
	{
		super(context);
		this.AwsAccessKeyId = AwsAccessKeyId;
		this.AwsSecretAccessKey = AwsSecretAccessKey;
		this.AwsEndpoint = AwsEndpoint;
		this.AwsRegion = AwsRegion;
		this.ThingName = ThingName;
		this.DesiredThingStatus = DesiredThingStatus;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        IoTConnector connector = new IoTConnector();
        connector.setLogger(Core.getLogger(UpdateThingState.class.getName()));
        connector.setCredentials(this.AwsAccessKeyId, this.AwsSecretAccessKey);
        connector.setRegion(this.AwsRegion);
        connector.setEndpoint(this.AwsEndpoint);
        String result = connector.updateThingShadow(this.ThingName, this.DesiredThingStatus);
        System.err.print(result);
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "UpdateThingState";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
