// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmqtt.proxies;

public class BME680
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bME680MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestMqtt.BME680";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Timestamp("Timestamp"),
		Temperature("Temperature"),
		Pressure("Pressure"),
		Humidity("Humidity"),
		Gas_resistance("Gas_resistance"),
		IAQ("IAQ"),
		Hostname("Hostname");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BME680(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestMqtt.BME680"));
	}

	protected BME680(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bME680MendixObject)
	{
		if (bME680MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestMqtt.BME680", bME680MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestMqtt.BME680");

		this.bME680MendixObject = bME680MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BME680.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testmqtt.proxies.BME680 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testmqtt.proxies.BME680.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testmqtt.proxies.BME680 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testmqtt.proxies.BME680(context, mendixObject);
	}

	public static testmqtt.proxies.BME680 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testmqtt.proxies.BME680.initialize(context, mendixObject);
	}

	public static java.util.List<testmqtt.proxies.BME680> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testmqtt.proxies.BME680> result = new java.util.ArrayList<testmqtt.proxies.BME680>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestMqtt.BME680" + xpathConstraint))
			result.add(testmqtt.proxies.BME680.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp()
	{
		return getTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Timestamp.toString());
	}

	/**
	 * Set value of Timestamp
	 * @param timestamp
	 */
	public final void setTimestamp(java.util.Date timestamp)
	{
		setTimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of Timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void setTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.Timestamp.toString(), timestamp);
	}

	/**
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature()
	{
		return getTemperature(getContext());
	}

	/**
	 * @param context
	 * @return value of Temperature
	 */
	public final java.math.BigDecimal getTemperature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temperature.toString());
	}

	/**
	 * Set value of Temperature
	 * @param temperature
	 */
	public final void setTemperature(java.math.BigDecimal temperature)
	{
		setTemperature(getContext(), temperature);
	}

	/**
	 * Set value of Temperature
	 * @param context
	 * @param temperature
	 */
	public final void setTemperature(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temperature)
	{
		getMendixObject().setValue(context, MemberNames.Temperature.toString(), temperature);
	}

	/**
	 * @return value of Pressure
	 */
	public final java.math.BigDecimal getPressure()
	{
		return getPressure(getContext());
	}

	/**
	 * @param context
	 * @return value of Pressure
	 */
	public final java.math.BigDecimal getPressure(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Pressure.toString());
	}

	/**
	 * Set value of Pressure
	 * @param pressure
	 */
	public final void setPressure(java.math.BigDecimal pressure)
	{
		setPressure(getContext(), pressure);
	}

	/**
	 * Set value of Pressure
	 * @param context
	 * @param pressure
	 */
	public final void setPressure(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal pressure)
	{
		getMendixObject().setValue(context, MemberNames.Pressure.toString(), pressure);
	}

	/**
	 * @return value of Humidity
	 */
	public final java.math.BigDecimal getHumidity()
	{
		return getHumidity(getContext());
	}

	/**
	 * @param context
	 * @return value of Humidity
	 */
	public final java.math.BigDecimal getHumidity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Humidity.toString());
	}

	/**
	 * Set value of Humidity
	 * @param humidity
	 */
	public final void setHumidity(java.math.BigDecimal humidity)
	{
		setHumidity(getContext(), humidity);
	}

	/**
	 * Set value of Humidity
	 * @param context
	 * @param humidity
	 */
	public final void setHumidity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal humidity)
	{
		getMendixObject().setValue(context, MemberNames.Humidity.toString(), humidity);
	}

	/**
	 * @return value of Gas_resistance
	 */
	public final java.math.BigDecimal getGas_resistance()
	{
		return getGas_resistance(getContext());
	}

	/**
	 * @param context
	 * @return value of Gas_resistance
	 */
	public final java.math.BigDecimal getGas_resistance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Gas_resistance.toString());
	}

	/**
	 * Set value of Gas_resistance
	 * @param gas_resistance
	 */
	public final void setGas_resistance(java.math.BigDecimal gas_resistance)
	{
		setGas_resistance(getContext(), gas_resistance);
	}

	/**
	 * Set value of Gas_resistance
	 * @param context
	 * @param gas_resistance
	 */
	public final void setGas_resistance(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal gas_resistance)
	{
		getMendixObject().setValue(context, MemberNames.Gas_resistance.toString(), gas_resistance);
	}

	/**
	 * @return value of IAQ
	 */
	public final java.math.BigDecimal getIAQ()
	{
		return getIAQ(getContext());
	}

	/**
	 * @param context
	 * @return value of IAQ
	 */
	public final java.math.BigDecimal getIAQ(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.IAQ.toString());
	}

	/**
	 * Set value of IAQ
	 * @param iaq
	 */
	public final void setIAQ(java.math.BigDecimal iaq)
	{
		setIAQ(getContext(), iaq);
	}

	/**
	 * Set value of IAQ
	 * @param context
	 * @param iaq
	 */
	public final void setIAQ(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal iaq)
	{
		getMendixObject().setValue(context, MemberNames.IAQ.toString(), iaq);
	}

	/**
	 * @return value of Hostname
	 */
	public final java.lang.String getHostname()
	{
		return getHostname(getContext());
	}

	/**
	 * @param context
	 * @return value of Hostname
	 */
	public final java.lang.String getHostname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Hostname.toString());
	}

	/**
	 * Set value of Hostname
	 * @param hostname
	 */
	public final void setHostname(java.lang.String hostname)
	{
		setHostname(getContext(), hostname);
	}

	/**
	 * Set value of Hostname
	 * @param context
	 * @param hostname
	 */
	public final void setHostname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hostname)
	{
		getMendixObject().setValue(context, MemberNames.Hostname.toString(), hostname);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bME680MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testmqtt.proxies.BME680 that = (testmqtt.proxies.BME680) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestMqtt.BME680";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
