// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmqtt.proxies;

public class Liveweer_10min
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject liveweer_10minMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestMqtt.Liveweer_10min";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Timestamp("Timestamp"),
		Plaats("Plaats"),
		Temp("Temp"),
		Gtemp("Gtemp"),
		Samenv("Samenv"),
		Lv("Lv"),
		Windr("Windr"),
		Windms("Windms"),
		Winds("Winds"),
		Windk("Windk"),
		Windkmh("Windkmh"),
		Luchtd("Luchtd"),
		Ldmmhg("Ldmmhg"),
		Dauwp("Dauwp"),
		Zicht("Zicht"),
		Verw("Verw"),
		Sup("Sup"),
		Sunder("Sunder"),
		Image("Image"),
		D0weer("D0weer"),
		D0tmax("D0tmax"),
		D0tmin("D0tmin"),
		D0windk("D0windk"),
		D0windknp("D0windknp"),
		D0windms("D0windms"),
		D0windkmh("D0windkmh"),
		D0windr("D0windr"),
		D0neerslag("D0neerslag"),
		D0zon("D0zon"),
		D1weer("D1weer"),
		D1tmax("D1tmax"),
		D1tmin("D1tmin"),
		D1windk("D1windk"),
		D1windknp("D1windknp"),
		D1windms("D1windms"),
		D1windkmh("D1windkmh"),
		D1windr("D1windr"),
		D1neerslag("D1neerslag"),
		D1zon("D1zon"),
		D2weer("D2weer"),
		D2tmax("D2tmax"),
		D2tmin("D2tmin"),
		D2windk("D2windk"),
		D2windknp("D2windknp"),
		D2windms("D2windms"),
		D2windkmh("D2windkmh"),
		D2windr("D2windr"),
		D2neerslag("D2neerslag"),
		D2zon("D2zon"),
		Alarm("Alarm");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Liveweer_10min(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestMqtt.Liveweer_10min"));
	}

	protected Liveweer_10min(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject liveweer_10minMendixObject)
	{
		if (liveweer_10minMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestMqtt.Liveweer_10min", liveweer_10minMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestMqtt.Liveweer_10min");

		this.liveweer_10minMendixObject = liveweer_10minMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Liveweer_10min.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testmqtt.proxies.Liveweer_10min initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testmqtt.proxies.Liveweer_10min.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testmqtt.proxies.Liveweer_10min initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testmqtt.proxies.Liveweer_10min(context, mendixObject);
	}

	public static testmqtt.proxies.Liveweer_10min load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testmqtt.proxies.Liveweer_10min.initialize(context, mendixObject);
	}

	public static java.util.List<testmqtt.proxies.Liveweer_10min> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testmqtt.proxies.Liveweer_10min> result = new java.util.ArrayList<testmqtt.proxies.Liveweer_10min>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestMqtt.Liveweer_10min" + xpathConstraint))
			result.add(testmqtt.proxies.Liveweer_10min.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp()
	{
		return getTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Timestamp.toString());
	}

	/**
	 * Set value of Timestamp
	 * @param timestamp
	 */
	public final void setTimestamp(java.util.Date timestamp)
	{
		setTimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of Timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void setTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.Timestamp.toString(), timestamp);
	}

	/**
	 * @return value of Plaats
	 */
	public final java.lang.String getPlaats()
	{
		return getPlaats(getContext());
	}

	/**
	 * @param context
	 * @return value of Plaats
	 */
	public final java.lang.String getPlaats(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Plaats.toString());
	}

	/**
	 * Set value of Plaats
	 * @param plaats
	 */
	public final void setPlaats(java.lang.String plaats)
	{
		setPlaats(getContext(), plaats);
	}

	/**
	 * Set value of Plaats
	 * @param context
	 * @param plaats
	 */
	public final void setPlaats(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plaats)
	{
		getMendixObject().setValue(context, MemberNames.Plaats.toString(), plaats);
	}

	/**
	 * @return value of Temp
	 */
	public final java.math.BigDecimal getTemp()
	{
		return getTemp(getContext());
	}

	/**
	 * @param context
	 * @return value of Temp
	 */
	public final java.math.BigDecimal getTemp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temp.toString());
	}

	/**
	 * Set value of Temp
	 * @param temp
	 */
	public final void setTemp(java.math.BigDecimal temp)
	{
		setTemp(getContext(), temp);
	}

	/**
	 * Set value of Temp
	 * @param context
	 * @param temp
	 */
	public final void setTemp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temp)
	{
		getMendixObject().setValue(context, MemberNames.Temp.toString(), temp);
	}

	/**
	 * @return value of Gtemp
	 */
	public final java.math.BigDecimal getGtemp()
	{
		return getGtemp(getContext());
	}

	/**
	 * @param context
	 * @return value of Gtemp
	 */
	public final java.math.BigDecimal getGtemp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Gtemp.toString());
	}

	/**
	 * Set value of Gtemp
	 * @param gtemp
	 */
	public final void setGtemp(java.math.BigDecimal gtemp)
	{
		setGtemp(getContext(), gtemp);
	}

	/**
	 * Set value of Gtemp
	 * @param context
	 * @param gtemp
	 */
	public final void setGtemp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal gtemp)
	{
		getMendixObject().setValue(context, MemberNames.Gtemp.toString(), gtemp);
	}

	/**
	 * @return value of Samenv
	 */
	public final java.lang.String getSamenv()
	{
		return getSamenv(getContext());
	}

	/**
	 * @param context
	 * @return value of Samenv
	 */
	public final java.lang.String getSamenv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Samenv.toString());
	}

	/**
	 * Set value of Samenv
	 * @param samenv
	 */
	public final void setSamenv(java.lang.String samenv)
	{
		setSamenv(getContext(), samenv);
	}

	/**
	 * Set value of Samenv
	 * @param context
	 * @param samenv
	 */
	public final void setSamenv(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String samenv)
	{
		getMendixObject().setValue(context, MemberNames.Samenv.toString(), samenv);
	}

	/**
	 * @return value of Lv
	 */
	public final java.math.BigDecimal getLv()
	{
		return getLv(getContext());
	}

	/**
	 * @param context
	 * @return value of Lv
	 */
	public final java.math.BigDecimal getLv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lv.toString());
	}

	/**
	 * Set value of Lv
	 * @param lv
	 */
	public final void setLv(java.math.BigDecimal lv)
	{
		setLv(getContext(), lv);
	}

	/**
	 * Set value of Lv
	 * @param context
	 * @param lv
	 */
	public final void setLv(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lv)
	{
		getMendixObject().setValue(context, MemberNames.Lv.toString(), lv);
	}

	/**
	 * @return value of Windr
	 */
	public final java.lang.String getWindr()
	{
		return getWindr(getContext());
	}

	/**
	 * @param context
	 * @return value of Windr
	 */
	public final java.lang.String getWindr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Windr.toString());
	}

	/**
	 * Set value of Windr
	 * @param windr
	 */
	public final void setWindr(java.lang.String windr)
	{
		setWindr(getContext(), windr);
	}

	/**
	 * Set value of Windr
	 * @param context
	 * @param windr
	 */
	public final void setWindr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String windr)
	{
		getMendixObject().setValue(context, MemberNames.Windr.toString(), windr);
	}

	/**
	 * @return value of Windms
	 */
	public final java.math.BigDecimal getWindms()
	{
		return getWindms(getContext());
	}

	/**
	 * @param context
	 * @return value of Windms
	 */
	public final java.math.BigDecimal getWindms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Windms.toString());
	}

	/**
	 * Set value of Windms
	 * @param windms
	 */
	public final void setWindms(java.math.BigDecimal windms)
	{
		setWindms(getContext(), windms);
	}

	/**
	 * Set value of Windms
	 * @param context
	 * @param windms
	 */
	public final void setWindms(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal windms)
	{
		getMendixObject().setValue(context, MemberNames.Windms.toString(), windms);
	}

	/**
	 * @return value of Winds
	 */
	public final java.math.BigDecimal getWinds()
	{
		return getWinds(getContext());
	}

	/**
	 * @param context
	 * @return value of Winds
	 */
	public final java.math.BigDecimal getWinds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Winds.toString());
	}

	/**
	 * Set value of Winds
	 * @param winds
	 */
	public final void setWinds(java.math.BigDecimal winds)
	{
		setWinds(getContext(), winds);
	}

	/**
	 * Set value of Winds
	 * @param context
	 * @param winds
	 */
	public final void setWinds(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal winds)
	{
		getMendixObject().setValue(context, MemberNames.Winds.toString(), winds);
	}

	/**
	 * @return value of Windk
	 */
	public final java.math.BigDecimal getWindk()
	{
		return getWindk(getContext());
	}

	/**
	 * @param context
	 * @return value of Windk
	 */
	public final java.math.BigDecimal getWindk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Windk.toString());
	}

	/**
	 * Set value of Windk
	 * @param windk
	 */
	public final void setWindk(java.math.BigDecimal windk)
	{
		setWindk(getContext(), windk);
	}

	/**
	 * Set value of Windk
	 * @param context
	 * @param windk
	 */
	public final void setWindk(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal windk)
	{
		getMendixObject().setValue(context, MemberNames.Windk.toString(), windk);
	}

	/**
	 * @return value of Windkmh
	 */
	public final java.math.BigDecimal getWindkmh()
	{
		return getWindkmh(getContext());
	}

	/**
	 * @param context
	 * @return value of Windkmh
	 */
	public final java.math.BigDecimal getWindkmh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Windkmh.toString());
	}

	/**
	 * Set value of Windkmh
	 * @param windkmh
	 */
	public final void setWindkmh(java.math.BigDecimal windkmh)
	{
		setWindkmh(getContext(), windkmh);
	}

	/**
	 * Set value of Windkmh
	 * @param context
	 * @param windkmh
	 */
	public final void setWindkmh(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal windkmh)
	{
		getMendixObject().setValue(context, MemberNames.Windkmh.toString(), windkmh);
	}

	/**
	 * @return value of Luchtd
	 */
	public final java.math.BigDecimal getLuchtd()
	{
		return getLuchtd(getContext());
	}

	/**
	 * @param context
	 * @return value of Luchtd
	 */
	public final java.math.BigDecimal getLuchtd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Luchtd.toString());
	}

	/**
	 * Set value of Luchtd
	 * @param luchtd
	 */
	public final void setLuchtd(java.math.BigDecimal luchtd)
	{
		setLuchtd(getContext(), luchtd);
	}

	/**
	 * Set value of Luchtd
	 * @param context
	 * @param luchtd
	 */
	public final void setLuchtd(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal luchtd)
	{
		getMendixObject().setValue(context, MemberNames.Luchtd.toString(), luchtd);
	}

	/**
	 * @return value of Ldmmhg
	 */
	public final java.math.BigDecimal getLdmmhg()
	{
		return getLdmmhg(getContext());
	}

	/**
	 * @param context
	 * @return value of Ldmmhg
	 */
	public final java.math.BigDecimal getLdmmhg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Ldmmhg.toString());
	}

	/**
	 * Set value of Ldmmhg
	 * @param ldmmhg
	 */
	public final void setLdmmhg(java.math.BigDecimal ldmmhg)
	{
		setLdmmhg(getContext(), ldmmhg);
	}

	/**
	 * Set value of Ldmmhg
	 * @param context
	 * @param ldmmhg
	 */
	public final void setLdmmhg(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ldmmhg)
	{
		getMendixObject().setValue(context, MemberNames.Ldmmhg.toString(), ldmmhg);
	}

	/**
	 * @return value of Dauwp
	 */
	public final java.math.BigDecimal getDauwp()
	{
		return getDauwp(getContext());
	}

	/**
	 * @param context
	 * @return value of Dauwp
	 */
	public final java.math.BigDecimal getDauwp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Dauwp.toString());
	}

	/**
	 * Set value of Dauwp
	 * @param dauwp
	 */
	public final void setDauwp(java.math.BigDecimal dauwp)
	{
		setDauwp(getContext(), dauwp);
	}

	/**
	 * Set value of Dauwp
	 * @param context
	 * @param dauwp
	 */
	public final void setDauwp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal dauwp)
	{
		getMendixObject().setValue(context, MemberNames.Dauwp.toString(), dauwp);
	}

	/**
	 * @return value of Zicht
	 */
	public final java.math.BigDecimal getZicht()
	{
		return getZicht(getContext());
	}

	/**
	 * @param context
	 * @return value of Zicht
	 */
	public final java.math.BigDecimal getZicht(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Zicht.toString());
	}

	/**
	 * Set value of Zicht
	 * @param zicht
	 */
	public final void setZicht(java.math.BigDecimal zicht)
	{
		setZicht(getContext(), zicht);
	}

	/**
	 * Set value of Zicht
	 * @param context
	 * @param zicht
	 */
	public final void setZicht(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal zicht)
	{
		getMendixObject().setValue(context, MemberNames.Zicht.toString(), zicht);
	}

	/**
	 * @return value of Verw
	 */
	public final java.lang.String getVerw()
	{
		return getVerw(getContext());
	}

	/**
	 * @param context
	 * @return value of Verw
	 */
	public final java.lang.String getVerw(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Verw.toString());
	}

	/**
	 * Set value of Verw
	 * @param verw
	 */
	public final void setVerw(java.lang.String verw)
	{
		setVerw(getContext(), verw);
	}

	/**
	 * Set value of Verw
	 * @param context
	 * @param verw
	 */
	public final void setVerw(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String verw)
	{
		getMendixObject().setValue(context, MemberNames.Verw.toString(), verw);
	}

	/**
	 * @return value of Sup
	 */
	public final java.lang.String getSup()
	{
		return getSup(getContext());
	}

	/**
	 * @param context
	 * @return value of Sup
	 */
	public final java.lang.String getSup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sup.toString());
	}

	/**
	 * Set value of Sup
	 * @param sup
	 */
	public final void setSup(java.lang.String sup)
	{
		setSup(getContext(), sup);
	}

	/**
	 * Set value of Sup
	 * @param context
	 * @param sup
	 */
	public final void setSup(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sup)
	{
		getMendixObject().setValue(context, MemberNames.Sup.toString(), sup);
	}

	/**
	 * @return value of Sunder
	 */
	public final java.lang.String getSunder()
	{
		return getSunder(getContext());
	}

	/**
	 * @param context
	 * @return value of Sunder
	 */
	public final java.lang.String getSunder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sunder.toString());
	}

	/**
	 * Set value of Sunder
	 * @param sunder
	 */
	public final void setSunder(java.lang.String sunder)
	{
		setSunder(getContext(), sunder);
	}

	/**
	 * Set value of Sunder
	 * @param context
	 * @param sunder
	 */
	public final void setSunder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sunder)
	{
		getMendixObject().setValue(context, MemberNames.Sunder.toString(), sunder);
	}

	/**
	 * @return value of Image
	 */
	public final java.lang.String getImage()
	{
		return getImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Image
	 */
	public final java.lang.String getImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Image.toString());
	}

	/**
	 * Set value of Image
	 * @param image
	 */
	public final void setImage(java.lang.String image)
	{
		setImage(getContext(), image);
	}

	/**
	 * Set value of Image
	 * @param context
	 * @param image
	 */
	public final void setImage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String image)
	{
		getMendixObject().setValue(context, MemberNames.Image.toString(), image);
	}

	/**
	 * @return value of D0weer
	 */
	public final java.lang.String getD0weer()
	{
		return getD0weer(getContext());
	}

	/**
	 * @param context
	 * @return value of D0weer
	 */
	public final java.lang.String getD0weer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.D0weer.toString());
	}

	/**
	 * Set value of D0weer
	 * @param d0weer
	 */
	public final void setD0weer(java.lang.String d0weer)
	{
		setD0weer(getContext(), d0weer);
	}

	/**
	 * Set value of D0weer
	 * @param context
	 * @param d0weer
	 */
	public final void setD0weer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String d0weer)
	{
		getMendixObject().setValue(context, MemberNames.D0weer.toString(), d0weer);
	}

	/**
	 * @return value of D0tmax
	 */
	public final java.math.BigDecimal getD0tmax()
	{
		return getD0tmax(getContext());
	}

	/**
	 * @param context
	 * @return value of D0tmax
	 */
	public final java.math.BigDecimal getD0tmax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D0tmax.toString());
	}

	/**
	 * Set value of D0tmax
	 * @param d0tmax
	 */
	public final void setD0tmax(java.math.BigDecimal d0tmax)
	{
		setD0tmax(getContext(), d0tmax);
	}

	/**
	 * Set value of D0tmax
	 * @param context
	 * @param d0tmax
	 */
	public final void setD0tmax(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d0tmax)
	{
		getMendixObject().setValue(context, MemberNames.D0tmax.toString(), d0tmax);
	}

	/**
	 * @return value of D0tmin
	 */
	public final java.math.BigDecimal getD0tmin()
	{
		return getD0tmin(getContext());
	}

	/**
	 * @param context
	 * @return value of D0tmin
	 */
	public final java.math.BigDecimal getD0tmin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D0tmin.toString());
	}

	/**
	 * Set value of D0tmin
	 * @param d0tmin
	 */
	public final void setD0tmin(java.math.BigDecimal d0tmin)
	{
		setD0tmin(getContext(), d0tmin);
	}

	/**
	 * Set value of D0tmin
	 * @param context
	 * @param d0tmin
	 */
	public final void setD0tmin(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d0tmin)
	{
		getMendixObject().setValue(context, MemberNames.D0tmin.toString(), d0tmin);
	}

	/**
	 * @return value of D0windk
	 */
	public final java.math.BigDecimal getD0windk()
	{
		return getD0windk(getContext());
	}

	/**
	 * @param context
	 * @return value of D0windk
	 */
	public final java.math.BigDecimal getD0windk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D0windk.toString());
	}

	/**
	 * Set value of D0windk
	 * @param d0windk
	 */
	public final void setD0windk(java.math.BigDecimal d0windk)
	{
		setD0windk(getContext(), d0windk);
	}

	/**
	 * Set value of D0windk
	 * @param context
	 * @param d0windk
	 */
	public final void setD0windk(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d0windk)
	{
		getMendixObject().setValue(context, MemberNames.D0windk.toString(), d0windk);
	}

	/**
	 * @return value of D0windknp
	 */
	public final java.math.BigDecimal getD0windknp()
	{
		return getD0windknp(getContext());
	}

	/**
	 * @param context
	 * @return value of D0windknp
	 */
	public final java.math.BigDecimal getD0windknp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D0windknp.toString());
	}

	/**
	 * Set value of D0windknp
	 * @param d0windknp
	 */
	public final void setD0windknp(java.math.BigDecimal d0windknp)
	{
		setD0windknp(getContext(), d0windknp);
	}

	/**
	 * Set value of D0windknp
	 * @param context
	 * @param d0windknp
	 */
	public final void setD0windknp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d0windknp)
	{
		getMendixObject().setValue(context, MemberNames.D0windknp.toString(), d0windknp);
	}

	/**
	 * @return value of D0windms
	 */
	public final java.math.BigDecimal getD0windms()
	{
		return getD0windms(getContext());
	}

	/**
	 * @param context
	 * @return value of D0windms
	 */
	public final java.math.BigDecimal getD0windms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D0windms.toString());
	}

	/**
	 * Set value of D0windms
	 * @param d0windms
	 */
	public final void setD0windms(java.math.BigDecimal d0windms)
	{
		setD0windms(getContext(), d0windms);
	}

	/**
	 * Set value of D0windms
	 * @param context
	 * @param d0windms
	 */
	public final void setD0windms(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d0windms)
	{
		getMendixObject().setValue(context, MemberNames.D0windms.toString(), d0windms);
	}

	/**
	 * @return value of D0windkmh
	 */
	public final java.math.BigDecimal getD0windkmh()
	{
		return getD0windkmh(getContext());
	}

	/**
	 * @param context
	 * @return value of D0windkmh
	 */
	public final java.math.BigDecimal getD0windkmh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D0windkmh.toString());
	}

	/**
	 * Set value of D0windkmh
	 * @param d0windkmh
	 */
	public final void setD0windkmh(java.math.BigDecimal d0windkmh)
	{
		setD0windkmh(getContext(), d0windkmh);
	}

	/**
	 * Set value of D0windkmh
	 * @param context
	 * @param d0windkmh
	 */
	public final void setD0windkmh(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d0windkmh)
	{
		getMendixObject().setValue(context, MemberNames.D0windkmh.toString(), d0windkmh);
	}

	/**
	 * @return value of D0windr
	 */
	public final java.lang.String getD0windr()
	{
		return getD0windr(getContext());
	}

	/**
	 * @param context
	 * @return value of D0windr
	 */
	public final java.lang.String getD0windr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.D0windr.toString());
	}

	/**
	 * Set value of D0windr
	 * @param d0windr
	 */
	public final void setD0windr(java.lang.String d0windr)
	{
		setD0windr(getContext(), d0windr);
	}

	/**
	 * Set value of D0windr
	 * @param context
	 * @param d0windr
	 */
	public final void setD0windr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String d0windr)
	{
		getMendixObject().setValue(context, MemberNames.D0windr.toString(), d0windr);
	}

	/**
	 * @return value of D0neerslag
	 */
	public final java.math.BigDecimal getD0neerslag()
	{
		return getD0neerslag(getContext());
	}

	/**
	 * @param context
	 * @return value of D0neerslag
	 */
	public final java.math.BigDecimal getD0neerslag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D0neerslag.toString());
	}

	/**
	 * Set value of D0neerslag
	 * @param d0neerslag
	 */
	public final void setD0neerslag(java.math.BigDecimal d0neerslag)
	{
		setD0neerslag(getContext(), d0neerslag);
	}

	/**
	 * Set value of D0neerslag
	 * @param context
	 * @param d0neerslag
	 */
	public final void setD0neerslag(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d0neerslag)
	{
		getMendixObject().setValue(context, MemberNames.D0neerslag.toString(), d0neerslag);
	}

	/**
	 * @return value of D0zon
	 */
	public final java.math.BigDecimal getD0zon()
	{
		return getD0zon(getContext());
	}

	/**
	 * @param context
	 * @return value of D0zon
	 */
	public final java.math.BigDecimal getD0zon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D0zon.toString());
	}

	/**
	 * Set value of D0zon
	 * @param d0zon
	 */
	public final void setD0zon(java.math.BigDecimal d0zon)
	{
		setD0zon(getContext(), d0zon);
	}

	/**
	 * Set value of D0zon
	 * @param context
	 * @param d0zon
	 */
	public final void setD0zon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d0zon)
	{
		getMendixObject().setValue(context, MemberNames.D0zon.toString(), d0zon);
	}

	/**
	 * @return value of D1weer
	 */
	public final java.lang.String getD1weer()
	{
		return getD1weer(getContext());
	}

	/**
	 * @param context
	 * @return value of D1weer
	 */
	public final java.lang.String getD1weer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.D1weer.toString());
	}

	/**
	 * Set value of D1weer
	 * @param d1weer
	 */
	public final void setD1weer(java.lang.String d1weer)
	{
		setD1weer(getContext(), d1weer);
	}

	/**
	 * Set value of D1weer
	 * @param context
	 * @param d1weer
	 */
	public final void setD1weer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String d1weer)
	{
		getMendixObject().setValue(context, MemberNames.D1weer.toString(), d1weer);
	}

	/**
	 * @return value of D1tmax
	 */
	public final java.math.BigDecimal getD1tmax()
	{
		return getD1tmax(getContext());
	}

	/**
	 * @param context
	 * @return value of D1tmax
	 */
	public final java.math.BigDecimal getD1tmax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D1tmax.toString());
	}

	/**
	 * Set value of D1tmax
	 * @param d1tmax
	 */
	public final void setD1tmax(java.math.BigDecimal d1tmax)
	{
		setD1tmax(getContext(), d1tmax);
	}

	/**
	 * Set value of D1tmax
	 * @param context
	 * @param d1tmax
	 */
	public final void setD1tmax(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d1tmax)
	{
		getMendixObject().setValue(context, MemberNames.D1tmax.toString(), d1tmax);
	}

	/**
	 * @return value of D1tmin
	 */
	public final java.math.BigDecimal getD1tmin()
	{
		return getD1tmin(getContext());
	}

	/**
	 * @param context
	 * @return value of D1tmin
	 */
	public final java.math.BigDecimal getD1tmin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D1tmin.toString());
	}

	/**
	 * Set value of D1tmin
	 * @param d1tmin
	 */
	public final void setD1tmin(java.math.BigDecimal d1tmin)
	{
		setD1tmin(getContext(), d1tmin);
	}

	/**
	 * Set value of D1tmin
	 * @param context
	 * @param d1tmin
	 */
	public final void setD1tmin(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d1tmin)
	{
		getMendixObject().setValue(context, MemberNames.D1tmin.toString(), d1tmin);
	}

	/**
	 * @return value of D1windk
	 */
	public final java.math.BigDecimal getD1windk()
	{
		return getD1windk(getContext());
	}

	/**
	 * @param context
	 * @return value of D1windk
	 */
	public final java.math.BigDecimal getD1windk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D1windk.toString());
	}

	/**
	 * Set value of D1windk
	 * @param d1windk
	 */
	public final void setD1windk(java.math.BigDecimal d1windk)
	{
		setD1windk(getContext(), d1windk);
	}

	/**
	 * Set value of D1windk
	 * @param context
	 * @param d1windk
	 */
	public final void setD1windk(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d1windk)
	{
		getMendixObject().setValue(context, MemberNames.D1windk.toString(), d1windk);
	}

	/**
	 * @return value of D1windknp
	 */
	public final java.math.BigDecimal getD1windknp()
	{
		return getD1windknp(getContext());
	}

	/**
	 * @param context
	 * @return value of D1windknp
	 */
	public final java.math.BigDecimal getD1windknp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D1windknp.toString());
	}

	/**
	 * Set value of D1windknp
	 * @param d1windknp
	 */
	public final void setD1windknp(java.math.BigDecimal d1windknp)
	{
		setD1windknp(getContext(), d1windknp);
	}

	/**
	 * Set value of D1windknp
	 * @param context
	 * @param d1windknp
	 */
	public final void setD1windknp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d1windknp)
	{
		getMendixObject().setValue(context, MemberNames.D1windknp.toString(), d1windknp);
	}

	/**
	 * @return value of D1windms
	 */
	public final java.math.BigDecimal getD1windms()
	{
		return getD1windms(getContext());
	}

	/**
	 * @param context
	 * @return value of D1windms
	 */
	public final java.math.BigDecimal getD1windms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D1windms.toString());
	}

	/**
	 * Set value of D1windms
	 * @param d1windms
	 */
	public final void setD1windms(java.math.BigDecimal d1windms)
	{
		setD1windms(getContext(), d1windms);
	}

	/**
	 * Set value of D1windms
	 * @param context
	 * @param d1windms
	 */
	public final void setD1windms(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d1windms)
	{
		getMendixObject().setValue(context, MemberNames.D1windms.toString(), d1windms);
	}

	/**
	 * @return value of D1windkmh
	 */
	public final java.math.BigDecimal getD1windkmh()
	{
		return getD1windkmh(getContext());
	}

	/**
	 * @param context
	 * @return value of D1windkmh
	 */
	public final java.math.BigDecimal getD1windkmh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D1windkmh.toString());
	}

	/**
	 * Set value of D1windkmh
	 * @param d1windkmh
	 */
	public final void setD1windkmh(java.math.BigDecimal d1windkmh)
	{
		setD1windkmh(getContext(), d1windkmh);
	}

	/**
	 * Set value of D1windkmh
	 * @param context
	 * @param d1windkmh
	 */
	public final void setD1windkmh(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d1windkmh)
	{
		getMendixObject().setValue(context, MemberNames.D1windkmh.toString(), d1windkmh);
	}

	/**
	 * @return value of D1windr
	 */
	public final java.lang.String getD1windr()
	{
		return getD1windr(getContext());
	}

	/**
	 * @param context
	 * @return value of D1windr
	 */
	public final java.lang.String getD1windr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.D1windr.toString());
	}

	/**
	 * Set value of D1windr
	 * @param d1windr
	 */
	public final void setD1windr(java.lang.String d1windr)
	{
		setD1windr(getContext(), d1windr);
	}

	/**
	 * Set value of D1windr
	 * @param context
	 * @param d1windr
	 */
	public final void setD1windr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String d1windr)
	{
		getMendixObject().setValue(context, MemberNames.D1windr.toString(), d1windr);
	}

	/**
	 * @return value of D1neerslag
	 */
	public final java.math.BigDecimal getD1neerslag()
	{
		return getD1neerslag(getContext());
	}

	/**
	 * @param context
	 * @return value of D1neerslag
	 */
	public final java.math.BigDecimal getD1neerslag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D1neerslag.toString());
	}

	/**
	 * Set value of D1neerslag
	 * @param d1neerslag
	 */
	public final void setD1neerslag(java.math.BigDecimal d1neerslag)
	{
		setD1neerslag(getContext(), d1neerslag);
	}

	/**
	 * Set value of D1neerslag
	 * @param context
	 * @param d1neerslag
	 */
	public final void setD1neerslag(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d1neerslag)
	{
		getMendixObject().setValue(context, MemberNames.D1neerslag.toString(), d1neerslag);
	}

	/**
	 * @return value of D1zon
	 */
	public final java.math.BigDecimal getD1zon()
	{
		return getD1zon(getContext());
	}

	/**
	 * @param context
	 * @return value of D1zon
	 */
	public final java.math.BigDecimal getD1zon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D1zon.toString());
	}

	/**
	 * Set value of D1zon
	 * @param d1zon
	 */
	public final void setD1zon(java.math.BigDecimal d1zon)
	{
		setD1zon(getContext(), d1zon);
	}

	/**
	 * Set value of D1zon
	 * @param context
	 * @param d1zon
	 */
	public final void setD1zon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d1zon)
	{
		getMendixObject().setValue(context, MemberNames.D1zon.toString(), d1zon);
	}

	/**
	 * @return value of D2weer
	 */
	public final java.lang.String getD2weer()
	{
		return getD2weer(getContext());
	}

	/**
	 * @param context
	 * @return value of D2weer
	 */
	public final java.lang.String getD2weer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.D2weer.toString());
	}

	/**
	 * Set value of D2weer
	 * @param d2weer
	 */
	public final void setD2weer(java.lang.String d2weer)
	{
		setD2weer(getContext(), d2weer);
	}

	/**
	 * Set value of D2weer
	 * @param context
	 * @param d2weer
	 */
	public final void setD2weer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String d2weer)
	{
		getMendixObject().setValue(context, MemberNames.D2weer.toString(), d2weer);
	}

	/**
	 * @return value of D2tmax
	 */
	public final java.math.BigDecimal getD2tmax()
	{
		return getD2tmax(getContext());
	}

	/**
	 * @param context
	 * @return value of D2tmax
	 */
	public final java.math.BigDecimal getD2tmax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D2tmax.toString());
	}

	/**
	 * Set value of D2tmax
	 * @param d2tmax
	 */
	public final void setD2tmax(java.math.BigDecimal d2tmax)
	{
		setD2tmax(getContext(), d2tmax);
	}

	/**
	 * Set value of D2tmax
	 * @param context
	 * @param d2tmax
	 */
	public final void setD2tmax(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d2tmax)
	{
		getMendixObject().setValue(context, MemberNames.D2tmax.toString(), d2tmax);
	}

	/**
	 * @return value of D2tmin
	 */
	public final java.math.BigDecimal getD2tmin()
	{
		return getD2tmin(getContext());
	}

	/**
	 * @param context
	 * @return value of D2tmin
	 */
	public final java.math.BigDecimal getD2tmin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D2tmin.toString());
	}

	/**
	 * Set value of D2tmin
	 * @param d2tmin
	 */
	public final void setD2tmin(java.math.BigDecimal d2tmin)
	{
		setD2tmin(getContext(), d2tmin);
	}

	/**
	 * Set value of D2tmin
	 * @param context
	 * @param d2tmin
	 */
	public final void setD2tmin(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d2tmin)
	{
		getMendixObject().setValue(context, MemberNames.D2tmin.toString(), d2tmin);
	}

	/**
	 * @return value of D2windk
	 */
	public final java.math.BigDecimal getD2windk()
	{
		return getD2windk(getContext());
	}

	/**
	 * @param context
	 * @return value of D2windk
	 */
	public final java.math.BigDecimal getD2windk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D2windk.toString());
	}

	/**
	 * Set value of D2windk
	 * @param d2windk
	 */
	public final void setD2windk(java.math.BigDecimal d2windk)
	{
		setD2windk(getContext(), d2windk);
	}

	/**
	 * Set value of D2windk
	 * @param context
	 * @param d2windk
	 */
	public final void setD2windk(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d2windk)
	{
		getMendixObject().setValue(context, MemberNames.D2windk.toString(), d2windk);
	}

	/**
	 * @return value of D2windknp
	 */
	public final java.math.BigDecimal getD2windknp()
	{
		return getD2windknp(getContext());
	}

	/**
	 * @param context
	 * @return value of D2windknp
	 */
	public final java.math.BigDecimal getD2windknp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D2windknp.toString());
	}

	/**
	 * Set value of D2windknp
	 * @param d2windknp
	 */
	public final void setD2windknp(java.math.BigDecimal d2windknp)
	{
		setD2windknp(getContext(), d2windknp);
	}

	/**
	 * Set value of D2windknp
	 * @param context
	 * @param d2windknp
	 */
	public final void setD2windknp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d2windknp)
	{
		getMendixObject().setValue(context, MemberNames.D2windknp.toString(), d2windknp);
	}

	/**
	 * @return value of D2windms
	 */
	public final java.math.BigDecimal getD2windms()
	{
		return getD2windms(getContext());
	}

	/**
	 * @param context
	 * @return value of D2windms
	 */
	public final java.math.BigDecimal getD2windms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D2windms.toString());
	}

	/**
	 * Set value of D2windms
	 * @param d2windms
	 */
	public final void setD2windms(java.math.BigDecimal d2windms)
	{
		setD2windms(getContext(), d2windms);
	}

	/**
	 * Set value of D2windms
	 * @param context
	 * @param d2windms
	 */
	public final void setD2windms(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d2windms)
	{
		getMendixObject().setValue(context, MemberNames.D2windms.toString(), d2windms);
	}

	/**
	 * @return value of D2windkmh
	 */
	public final java.math.BigDecimal getD2windkmh()
	{
		return getD2windkmh(getContext());
	}

	/**
	 * @param context
	 * @return value of D2windkmh
	 */
	public final java.math.BigDecimal getD2windkmh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D2windkmh.toString());
	}

	/**
	 * Set value of D2windkmh
	 * @param d2windkmh
	 */
	public final void setD2windkmh(java.math.BigDecimal d2windkmh)
	{
		setD2windkmh(getContext(), d2windkmh);
	}

	/**
	 * Set value of D2windkmh
	 * @param context
	 * @param d2windkmh
	 */
	public final void setD2windkmh(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d2windkmh)
	{
		getMendixObject().setValue(context, MemberNames.D2windkmh.toString(), d2windkmh);
	}

	/**
	 * @return value of D2windr
	 */
	public final java.lang.String getD2windr()
	{
		return getD2windr(getContext());
	}

	/**
	 * @param context
	 * @return value of D2windr
	 */
	public final java.lang.String getD2windr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.D2windr.toString());
	}

	/**
	 * Set value of D2windr
	 * @param d2windr
	 */
	public final void setD2windr(java.lang.String d2windr)
	{
		setD2windr(getContext(), d2windr);
	}

	/**
	 * Set value of D2windr
	 * @param context
	 * @param d2windr
	 */
	public final void setD2windr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String d2windr)
	{
		getMendixObject().setValue(context, MemberNames.D2windr.toString(), d2windr);
	}

	/**
	 * @return value of D2neerslag
	 */
	public final java.math.BigDecimal getD2neerslag()
	{
		return getD2neerslag(getContext());
	}

	/**
	 * @param context
	 * @return value of D2neerslag
	 */
	public final java.math.BigDecimal getD2neerslag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D2neerslag.toString());
	}

	/**
	 * Set value of D2neerslag
	 * @param d2neerslag
	 */
	public final void setD2neerslag(java.math.BigDecimal d2neerslag)
	{
		setD2neerslag(getContext(), d2neerslag);
	}

	/**
	 * Set value of D2neerslag
	 * @param context
	 * @param d2neerslag
	 */
	public final void setD2neerslag(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d2neerslag)
	{
		getMendixObject().setValue(context, MemberNames.D2neerslag.toString(), d2neerslag);
	}

	/**
	 * @return value of D2zon
	 */
	public final java.math.BigDecimal getD2zon()
	{
		return getD2zon(getContext());
	}

	/**
	 * @param context
	 * @return value of D2zon
	 */
	public final java.math.BigDecimal getD2zon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.D2zon.toString());
	}

	/**
	 * Set value of D2zon
	 * @param d2zon
	 */
	public final void setD2zon(java.math.BigDecimal d2zon)
	{
		setD2zon(getContext(), d2zon);
	}

	/**
	 * Set value of D2zon
	 * @param context
	 * @param d2zon
	 */
	public final void setD2zon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal d2zon)
	{
		getMendixObject().setValue(context, MemberNames.D2zon.toString(), d2zon);
	}

	/**
	 * @return value of Alarm
	 */
	public final java.math.BigDecimal getAlarm()
	{
		return getAlarm(getContext());
	}

	/**
	 * @param context
	 * @return value of Alarm
	 */
	public final java.math.BigDecimal getAlarm(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Alarm.toString());
	}

	/**
	 * Set value of Alarm
	 * @param alarm
	 */
	public final void setAlarm(java.math.BigDecimal alarm)
	{
		setAlarm(getContext(), alarm);
	}

	/**
	 * Set value of Alarm
	 * @param context
	 * @param alarm
	 */
	public final void setAlarm(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal alarm)
	{
		getMendixObject().setValue(context, MemberNames.Alarm.toString(), alarm);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return liveweer_10minMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testmqtt.proxies.Liveweer_10min that = (testmqtt.proxies.Liveweer_10min) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestMqtt.Liveweer_10min";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
