// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmqtt.proxies;

public class Meteoserver_zeeweer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject meteoserver_zeeweerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestMqtt.Meteoserver_zeeweer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Timestamp("Timestamp"),
		Plaats("Plaats"),
		Code("Code"),
		_type("_type"),
		Temp("Temp"),
		Gtemp("Gtemp"),
		Samenv("Samenv"),
		Lv("Lv"),
		Windr("Windr"),
		Windms("Windms"),
		Winds("Winds"),
		Windk("Windk"),
		Windkmh("Windkmh"),
		Luchtd("Luchtd"),
		Ldmmhg("Ldmmhg"),
		Dauwp("Dauwp"),
		Zicht("Zicht"),
		Verw("Verw"),
		Sup("Sup"),
		Sunder("Sunder"),
		Image("Image"),
		Golfsig("Golfsig"),
		Rsig("Rsig"),
		Rsigltr("Rsigltr"),
		Psig("Psig"),
		Piekfreq("Piekfreq"),
		Swell("Swell"),
		Srichting("Srichting"),
		Srichtingltr("Srichtingltr"),
		Wtemp("Wtemp"),
		Waarsch("Waarsch"),
		Wsch_kust("Wsch_kust"),
		Wsch_nrdz("Wsch_nrdz"),
		Wsch_kust_bijgw("Wsch_kust_bijgw"),
		Wsch_nrdz_bijgw("Wsch_nrdz_bijgw");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Meteoserver_zeeweer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestMqtt.Meteoserver_zeeweer"));
	}

	protected Meteoserver_zeeweer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject meteoserver_zeeweerMendixObject)
	{
		if (meteoserver_zeeweerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestMqtt.Meteoserver_zeeweer", meteoserver_zeeweerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestMqtt.Meteoserver_zeeweer");

		this.meteoserver_zeeweerMendixObject = meteoserver_zeeweerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Meteoserver_zeeweer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static testmqtt.proxies.Meteoserver_zeeweer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testmqtt.proxies.Meteoserver_zeeweer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static testmqtt.proxies.Meteoserver_zeeweer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testmqtt.proxies.Meteoserver_zeeweer(context, mendixObject);
	}

	public static testmqtt.proxies.Meteoserver_zeeweer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testmqtt.proxies.Meteoserver_zeeweer.initialize(context, mendixObject);
	}

	public static java.util.List<testmqtt.proxies.Meteoserver_zeeweer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<testmqtt.proxies.Meteoserver_zeeweer> result = new java.util.ArrayList<testmqtt.proxies.Meteoserver_zeeweer>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TestMqtt.Meteoserver_zeeweer" + xpathConstraint))
			result.add(testmqtt.proxies.Meteoserver_zeeweer.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp()
	{
		return getTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Timestamp.toString());
	}

	/**
	 * Set value of Timestamp
	 * @param timestamp
	 */
	public final void setTimestamp(java.util.Date timestamp)
	{
		setTimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of Timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void setTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.Timestamp.toString(), timestamp);
	}

	/**
	 * @return value of Plaats
	 */
	public final java.lang.String getPlaats()
	{
		return getPlaats(getContext());
	}

	/**
	 * @param context
	 * @return value of Plaats
	 */
	public final java.lang.String getPlaats(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Plaats.toString());
	}

	/**
	 * Set value of Plaats
	 * @param plaats
	 */
	public final void setPlaats(java.lang.String plaats)
	{
		setPlaats(getContext(), plaats);
	}

	/**
	 * Set value of Plaats
	 * @param context
	 * @param plaats
	 */
	public final void setPlaats(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plaats)
	{
		getMendixObject().setValue(context, MemberNames.Plaats.toString(), plaats);
	}

	/**
	 * @return value of Code
	 */
	public final java.lang.String getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.String getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.String code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Temp
	 */
	public final java.math.BigDecimal getTemp()
	{
		return getTemp(getContext());
	}

	/**
	 * @param context
	 * @return value of Temp
	 */
	public final java.math.BigDecimal getTemp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Temp.toString());
	}

	/**
	 * Set value of Temp
	 * @param temp
	 */
	public final void setTemp(java.math.BigDecimal temp)
	{
		setTemp(getContext(), temp);
	}

	/**
	 * Set value of Temp
	 * @param context
	 * @param temp
	 */
	public final void setTemp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal temp)
	{
		getMendixObject().setValue(context, MemberNames.Temp.toString(), temp);
	}

	/**
	 * @return value of Gtemp
	 */
	public final java.math.BigDecimal getGtemp()
	{
		return getGtemp(getContext());
	}

	/**
	 * @param context
	 * @return value of Gtemp
	 */
	public final java.math.BigDecimal getGtemp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Gtemp.toString());
	}

	/**
	 * Set value of Gtemp
	 * @param gtemp
	 */
	public final void setGtemp(java.math.BigDecimal gtemp)
	{
		setGtemp(getContext(), gtemp);
	}

	/**
	 * Set value of Gtemp
	 * @param context
	 * @param gtemp
	 */
	public final void setGtemp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal gtemp)
	{
		getMendixObject().setValue(context, MemberNames.Gtemp.toString(), gtemp);
	}

	/**
	 * @return value of Samenv
	 */
	public final java.lang.String getSamenv()
	{
		return getSamenv(getContext());
	}

	/**
	 * @param context
	 * @return value of Samenv
	 */
	public final java.lang.String getSamenv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Samenv.toString());
	}

	/**
	 * Set value of Samenv
	 * @param samenv
	 */
	public final void setSamenv(java.lang.String samenv)
	{
		setSamenv(getContext(), samenv);
	}

	/**
	 * Set value of Samenv
	 * @param context
	 * @param samenv
	 */
	public final void setSamenv(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String samenv)
	{
		getMendixObject().setValue(context, MemberNames.Samenv.toString(), samenv);
	}

	/**
	 * @return value of Lv
	 */
	public final java.math.BigDecimal getLv()
	{
		return getLv(getContext());
	}

	/**
	 * @param context
	 * @return value of Lv
	 */
	public final java.math.BigDecimal getLv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lv.toString());
	}

	/**
	 * Set value of Lv
	 * @param lv
	 */
	public final void setLv(java.math.BigDecimal lv)
	{
		setLv(getContext(), lv);
	}

	/**
	 * Set value of Lv
	 * @param context
	 * @param lv
	 */
	public final void setLv(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lv)
	{
		getMendixObject().setValue(context, MemberNames.Lv.toString(), lv);
	}

	/**
	 * @return value of Windr
	 */
	public final java.lang.String getWindr()
	{
		return getWindr(getContext());
	}

	/**
	 * @param context
	 * @return value of Windr
	 */
	public final java.lang.String getWindr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Windr.toString());
	}

	/**
	 * Set value of Windr
	 * @param windr
	 */
	public final void setWindr(java.lang.String windr)
	{
		setWindr(getContext(), windr);
	}

	/**
	 * Set value of Windr
	 * @param context
	 * @param windr
	 */
	public final void setWindr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String windr)
	{
		getMendixObject().setValue(context, MemberNames.Windr.toString(), windr);
	}

	/**
	 * @return value of Windms
	 */
	public final java.math.BigDecimal getWindms()
	{
		return getWindms(getContext());
	}

	/**
	 * @param context
	 * @return value of Windms
	 */
	public final java.math.BigDecimal getWindms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Windms.toString());
	}

	/**
	 * Set value of Windms
	 * @param windms
	 */
	public final void setWindms(java.math.BigDecimal windms)
	{
		setWindms(getContext(), windms);
	}

	/**
	 * Set value of Windms
	 * @param context
	 * @param windms
	 */
	public final void setWindms(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal windms)
	{
		getMendixObject().setValue(context, MemberNames.Windms.toString(), windms);
	}

	/**
	 * @return value of Winds
	 */
	public final java.math.BigDecimal getWinds()
	{
		return getWinds(getContext());
	}

	/**
	 * @param context
	 * @return value of Winds
	 */
	public final java.math.BigDecimal getWinds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Winds.toString());
	}

	/**
	 * Set value of Winds
	 * @param winds
	 */
	public final void setWinds(java.math.BigDecimal winds)
	{
		setWinds(getContext(), winds);
	}

	/**
	 * Set value of Winds
	 * @param context
	 * @param winds
	 */
	public final void setWinds(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal winds)
	{
		getMendixObject().setValue(context, MemberNames.Winds.toString(), winds);
	}

	/**
	 * @return value of Windk
	 */
	public final java.math.BigDecimal getWindk()
	{
		return getWindk(getContext());
	}

	/**
	 * @param context
	 * @return value of Windk
	 */
	public final java.math.BigDecimal getWindk(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Windk.toString());
	}

	/**
	 * Set value of Windk
	 * @param windk
	 */
	public final void setWindk(java.math.BigDecimal windk)
	{
		setWindk(getContext(), windk);
	}

	/**
	 * Set value of Windk
	 * @param context
	 * @param windk
	 */
	public final void setWindk(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal windk)
	{
		getMendixObject().setValue(context, MemberNames.Windk.toString(), windk);
	}

	/**
	 * @return value of Windkmh
	 */
	public final java.math.BigDecimal getWindkmh()
	{
		return getWindkmh(getContext());
	}

	/**
	 * @param context
	 * @return value of Windkmh
	 */
	public final java.math.BigDecimal getWindkmh(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Windkmh.toString());
	}

	/**
	 * Set value of Windkmh
	 * @param windkmh
	 */
	public final void setWindkmh(java.math.BigDecimal windkmh)
	{
		setWindkmh(getContext(), windkmh);
	}

	/**
	 * Set value of Windkmh
	 * @param context
	 * @param windkmh
	 */
	public final void setWindkmh(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal windkmh)
	{
		getMendixObject().setValue(context, MemberNames.Windkmh.toString(), windkmh);
	}

	/**
	 * @return value of Luchtd
	 */
	public final java.math.BigDecimal getLuchtd()
	{
		return getLuchtd(getContext());
	}

	/**
	 * @param context
	 * @return value of Luchtd
	 */
	public final java.math.BigDecimal getLuchtd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Luchtd.toString());
	}

	/**
	 * Set value of Luchtd
	 * @param luchtd
	 */
	public final void setLuchtd(java.math.BigDecimal luchtd)
	{
		setLuchtd(getContext(), luchtd);
	}

	/**
	 * Set value of Luchtd
	 * @param context
	 * @param luchtd
	 */
	public final void setLuchtd(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal luchtd)
	{
		getMendixObject().setValue(context, MemberNames.Luchtd.toString(), luchtd);
	}

	/**
	 * @return value of Ldmmhg
	 */
	public final java.math.BigDecimal getLdmmhg()
	{
		return getLdmmhg(getContext());
	}

	/**
	 * @param context
	 * @return value of Ldmmhg
	 */
	public final java.math.BigDecimal getLdmmhg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Ldmmhg.toString());
	}

	/**
	 * Set value of Ldmmhg
	 * @param ldmmhg
	 */
	public final void setLdmmhg(java.math.BigDecimal ldmmhg)
	{
		setLdmmhg(getContext(), ldmmhg);
	}

	/**
	 * Set value of Ldmmhg
	 * @param context
	 * @param ldmmhg
	 */
	public final void setLdmmhg(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ldmmhg)
	{
		getMendixObject().setValue(context, MemberNames.Ldmmhg.toString(), ldmmhg);
	}

	/**
	 * @return value of Dauwp
	 */
	public final java.math.BigDecimal getDauwp()
	{
		return getDauwp(getContext());
	}

	/**
	 * @param context
	 * @return value of Dauwp
	 */
	public final java.math.BigDecimal getDauwp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Dauwp.toString());
	}

	/**
	 * Set value of Dauwp
	 * @param dauwp
	 */
	public final void setDauwp(java.math.BigDecimal dauwp)
	{
		setDauwp(getContext(), dauwp);
	}

	/**
	 * Set value of Dauwp
	 * @param context
	 * @param dauwp
	 */
	public final void setDauwp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal dauwp)
	{
		getMendixObject().setValue(context, MemberNames.Dauwp.toString(), dauwp);
	}

	/**
	 * @return value of Zicht
	 */
	public final java.math.BigDecimal getZicht()
	{
		return getZicht(getContext());
	}

	/**
	 * @param context
	 * @return value of Zicht
	 */
	public final java.math.BigDecimal getZicht(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Zicht.toString());
	}

	/**
	 * Set value of Zicht
	 * @param zicht
	 */
	public final void setZicht(java.math.BigDecimal zicht)
	{
		setZicht(getContext(), zicht);
	}

	/**
	 * Set value of Zicht
	 * @param context
	 * @param zicht
	 */
	public final void setZicht(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal zicht)
	{
		getMendixObject().setValue(context, MemberNames.Zicht.toString(), zicht);
	}

	/**
	 * @return value of Verw
	 */
	public final java.lang.String getVerw()
	{
		return getVerw(getContext());
	}

	/**
	 * @param context
	 * @return value of Verw
	 */
	public final java.lang.String getVerw(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Verw.toString());
	}

	/**
	 * Set value of Verw
	 * @param verw
	 */
	public final void setVerw(java.lang.String verw)
	{
		setVerw(getContext(), verw);
	}

	/**
	 * Set value of Verw
	 * @param context
	 * @param verw
	 */
	public final void setVerw(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String verw)
	{
		getMendixObject().setValue(context, MemberNames.Verw.toString(), verw);
	}

	/**
	 * @return value of Sup
	 */
	public final java.lang.String getSup()
	{
		return getSup(getContext());
	}

	/**
	 * @param context
	 * @return value of Sup
	 */
	public final java.lang.String getSup(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sup.toString());
	}

	/**
	 * Set value of Sup
	 * @param sup
	 */
	public final void setSup(java.lang.String sup)
	{
		setSup(getContext(), sup);
	}

	/**
	 * Set value of Sup
	 * @param context
	 * @param sup
	 */
	public final void setSup(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sup)
	{
		getMendixObject().setValue(context, MemberNames.Sup.toString(), sup);
	}

	/**
	 * @return value of Sunder
	 */
	public final java.lang.String getSunder()
	{
		return getSunder(getContext());
	}

	/**
	 * @param context
	 * @return value of Sunder
	 */
	public final java.lang.String getSunder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sunder.toString());
	}

	/**
	 * Set value of Sunder
	 * @param sunder
	 */
	public final void setSunder(java.lang.String sunder)
	{
		setSunder(getContext(), sunder);
	}

	/**
	 * Set value of Sunder
	 * @param context
	 * @param sunder
	 */
	public final void setSunder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sunder)
	{
		getMendixObject().setValue(context, MemberNames.Sunder.toString(), sunder);
	}

	/**
	 * @return value of Image
	 */
	public final java.lang.String getImage()
	{
		return getImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Image
	 */
	public final java.lang.String getImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Image.toString());
	}

	/**
	 * Set value of Image
	 * @param image
	 */
	public final void setImage(java.lang.String image)
	{
		setImage(getContext(), image);
	}

	/**
	 * Set value of Image
	 * @param context
	 * @param image
	 */
	public final void setImage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String image)
	{
		getMendixObject().setValue(context, MemberNames.Image.toString(), image);
	}

	/**
	 * @return value of Golfsig
	 */
	public final java.math.BigDecimal getGolfsig()
	{
		return getGolfsig(getContext());
	}

	/**
	 * @param context
	 * @return value of Golfsig
	 */
	public final java.math.BigDecimal getGolfsig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Golfsig.toString());
	}

	/**
	 * Set value of Golfsig
	 * @param golfsig
	 */
	public final void setGolfsig(java.math.BigDecimal golfsig)
	{
		setGolfsig(getContext(), golfsig);
	}

	/**
	 * Set value of Golfsig
	 * @param context
	 * @param golfsig
	 */
	public final void setGolfsig(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal golfsig)
	{
		getMendixObject().setValue(context, MemberNames.Golfsig.toString(), golfsig);
	}

	/**
	 * @return value of Rsig
	 */
	public final java.math.BigDecimal getRsig()
	{
		return getRsig(getContext());
	}

	/**
	 * @param context
	 * @return value of Rsig
	 */
	public final java.math.BigDecimal getRsig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Rsig.toString());
	}

	/**
	 * Set value of Rsig
	 * @param rsig
	 */
	public final void setRsig(java.math.BigDecimal rsig)
	{
		setRsig(getContext(), rsig);
	}

	/**
	 * Set value of Rsig
	 * @param context
	 * @param rsig
	 */
	public final void setRsig(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal rsig)
	{
		getMendixObject().setValue(context, MemberNames.Rsig.toString(), rsig);
	}

	/**
	 * @return value of Rsigltr
	 */
	public final java.lang.String getRsigltr()
	{
		return getRsigltr(getContext());
	}

	/**
	 * @param context
	 * @return value of Rsigltr
	 */
	public final java.lang.String getRsigltr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Rsigltr.toString());
	}

	/**
	 * Set value of Rsigltr
	 * @param rsigltr
	 */
	public final void setRsigltr(java.lang.String rsigltr)
	{
		setRsigltr(getContext(), rsigltr);
	}

	/**
	 * Set value of Rsigltr
	 * @param context
	 * @param rsigltr
	 */
	public final void setRsigltr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rsigltr)
	{
		getMendixObject().setValue(context, MemberNames.Rsigltr.toString(), rsigltr);
	}

	/**
	 * @return value of Psig
	 */
	public final java.math.BigDecimal getPsig()
	{
		return getPsig(getContext());
	}

	/**
	 * @param context
	 * @return value of Psig
	 */
	public final java.math.BigDecimal getPsig(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Psig.toString());
	}

	/**
	 * Set value of Psig
	 * @param psig
	 */
	public final void setPsig(java.math.BigDecimal psig)
	{
		setPsig(getContext(), psig);
	}

	/**
	 * Set value of Psig
	 * @param context
	 * @param psig
	 */
	public final void setPsig(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal psig)
	{
		getMendixObject().setValue(context, MemberNames.Psig.toString(), psig);
	}

	/**
	 * @return value of Piekfreq
	 */
	public final java.math.BigDecimal getPiekfreq()
	{
		return getPiekfreq(getContext());
	}

	/**
	 * @param context
	 * @return value of Piekfreq
	 */
	public final java.math.BigDecimal getPiekfreq(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Piekfreq.toString());
	}

	/**
	 * Set value of Piekfreq
	 * @param piekfreq
	 */
	public final void setPiekfreq(java.math.BigDecimal piekfreq)
	{
		setPiekfreq(getContext(), piekfreq);
	}

	/**
	 * Set value of Piekfreq
	 * @param context
	 * @param piekfreq
	 */
	public final void setPiekfreq(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal piekfreq)
	{
		getMendixObject().setValue(context, MemberNames.Piekfreq.toString(), piekfreq);
	}

	/**
	 * @return value of Swell
	 */
	public final java.math.BigDecimal getSwell()
	{
		return getSwell(getContext());
	}

	/**
	 * @param context
	 * @return value of Swell
	 */
	public final java.math.BigDecimal getSwell(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Swell.toString());
	}

	/**
	 * Set value of Swell
	 * @param swell
	 */
	public final void setSwell(java.math.BigDecimal swell)
	{
		setSwell(getContext(), swell);
	}

	/**
	 * Set value of Swell
	 * @param context
	 * @param swell
	 */
	public final void setSwell(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal swell)
	{
		getMendixObject().setValue(context, MemberNames.Swell.toString(), swell);
	}

	/**
	 * @return value of Srichting
	 */
	public final java.math.BigDecimal getSrichting()
	{
		return getSrichting(getContext());
	}

	/**
	 * @param context
	 * @return value of Srichting
	 */
	public final java.math.BigDecimal getSrichting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Srichting.toString());
	}

	/**
	 * Set value of Srichting
	 * @param srichting
	 */
	public final void setSrichting(java.math.BigDecimal srichting)
	{
		setSrichting(getContext(), srichting);
	}

	/**
	 * Set value of Srichting
	 * @param context
	 * @param srichting
	 */
	public final void setSrichting(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal srichting)
	{
		getMendixObject().setValue(context, MemberNames.Srichting.toString(), srichting);
	}

	/**
	 * @return value of Srichtingltr
	 */
	public final java.lang.String getSrichtingltr()
	{
		return getSrichtingltr(getContext());
	}

	/**
	 * @param context
	 * @return value of Srichtingltr
	 */
	public final java.lang.String getSrichtingltr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Srichtingltr.toString());
	}

	/**
	 * Set value of Srichtingltr
	 * @param srichtingltr
	 */
	public final void setSrichtingltr(java.lang.String srichtingltr)
	{
		setSrichtingltr(getContext(), srichtingltr);
	}

	/**
	 * Set value of Srichtingltr
	 * @param context
	 * @param srichtingltr
	 */
	public final void setSrichtingltr(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String srichtingltr)
	{
		getMendixObject().setValue(context, MemberNames.Srichtingltr.toString(), srichtingltr);
	}

	/**
	 * @return value of Wtemp
	 */
	public final java.math.BigDecimal getWtemp()
	{
		return getWtemp(getContext());
	}

	/**
	 * @param context
	 * @return value of Wtemp
	 */
	public final java.math.BigDecimal getWtemp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Wtemp.toString());
	}

	/**
	 * Set value of Wtemp
	 * @param wtemp
	 */
	public final void setWtemp(java.math.BigDecimal wtemp)
	{
		setWtemp(getContext(), wtemp);
	}

	/**
	 * Set value of Wtemp
	 * @param context
	 * @param wtemp
	 */
	public final void setWtemp(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal wtemp)
	{
		getMendixObject().setValue(context, MemberNames.Wtemp.toString(), wtemp);
	}

	/**
	 * @return value of Waarsch
	 */
	public final java.lang.String getWaarsch()
	{
		return getWaarsch(getContext());
	}

	/**
	 * @param context
	 * @return value of Waarsch
	 */
	public final java.lang.String getWaarsch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Waarsch.toString());
	}

	/**
	 * Set value of Waarsch
	 * @param waarsch
	 */
	public final void setWaarsch(java.lang.String waarsch)
	{
		setWaarsch(getContext(), waarsch);
	}

	/**
	 * Set value of Waarsch
	 * @param context
	 * @param waarsch
	 */
	public final void setWaarsch(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String waarsch)
	{
		getMendixObject().setValue(context, MemberNames.Waarsch.toString(), waarsch);
	}

	/**
	 * @return value of Wsch_kust
	 */
	public final java.lang.String getWsch_kust()
	{
		return getWsch_kust(getContext());
	}

	/**
	 * @param context
	 * @return value of Wsch_kust
	 */
	public final java.lang.String getWsch_kust(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Wsch_kust.toString());
	}

	/**
	 * Set value of Wsch_kust
	 * @param wsch_kust
	 */
	public final void setWsch_kust(java.lang.String wsch_kust)
	{
		setWsch_kust(getContext(), wsch_kust);
	}

	/**
	 * Set value of Wsch_kust
	 * @param context
	 * @param wsch_kust
	 */
	public final void setWsch_kust(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wsch_kust)
	{
		getMendixObject().setValue(context, MemberNames.Wsch_kust.toString(), wsch_kust);
	}

	/**
	 * @return value of Wsch_nrdz
	 */
	public final java.lang.String getWsch_nrdz()
	{
		return getWsch_nrdz(getContext());
	}

	/**
	 * @param context
	 * @return value of Wsch_nrdz
	 */
	public final java.lang.String getWsch_nrdz(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Wsch_nrdz.toString());
	}

	/**
	 * Set value of Wsch_nrdz
	 * @param wsch_nrdz
	 */
	public final void setWsch_nrdz(java.lang.String wsch_nrdz)
	{
		setWsch_nrdz(getContext(), wsch_nrdz);
	}

	/**
	 * Set value of Wsch_nrdz
	 * @param context
	 * @param wsch_nrdz
	 */
	public final void setWsch_nrdz(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wsch_nrdz)
	{
		getMendixObject().setValue(context, MemberNames.Wsch_nrdz.toString(), wsch_nrdz);
	}

	/**
	 * @return value of Wsch_kust_bijgw
	 */
	public final java.lang.String getWsch_kust_bijgw()
	{
		return getWsch_kust_bijgw(getContext());
	}

	/**
	 * @param context
	 * @return value of Wsch_kust_bijgw
	 */
	public final java.lang.String getWsch_kust_bijgw(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Wsch_kust_bijgw.toString());
	}

	/**
	 * Set value of Wsch_kust_bijgw
	 * @param wsch_kust_bijgw
	 */
	public final void setWsch_kust_bijgw(java.lang.String wsch_kust_bijgw)
	{
		setWsch_kust_bijgw(getContext(), wsch_kust_bijgw);
	}

	/**
	 * Set value of Wsch_kust_bijgw
	 * @param context
	 * @param wsch_kust_bijgw
	 */
	public final void setWsch_kust_bijgw(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wsch_kust_bijgw)
	{
		getMendixObject().setValue(context, MemberNames.Wsch_kust_bijgw.toString(), wsch_kust_bijgw);
	}

	/**
	 * @return value of Wsch_nrdz_bijgw
	 */
	public final java.lang.String getWsch_nrdz_bijgw()
	{
		return getWsch_nrdz_bijgw(getContext());
	}

	/**
	 * @param context
	 * @return value of Wsch_nrdz_bijgw
	 */
	public final java.lang.String getWsch_nrdz_bijgw(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Wsch_nrdz_bijgw.toString());
	}

	/**
	 * Set value of Wsch_nrdz_bijgw
	 * @param wsch_nrdz_bijgw
	 */
	public final void setWsch_nrdz_bijgw(java.lang.String wsch_nrdz_bijgw)
	{
		setWsch_nrdz_bijgw(getContext(), wsch_nrdz_bijgw);
	}

	/**
	 * Set value of Wsch_nrdz_bijgw
	 * @param context
	 * @param wsch_nrdz_bijgw
	 */
	public final void setWsch_nrdz_bijgw(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String wsch_nrdz_bijgw)
	{
		getMendixObject().setValue(context, MemberNames.Wsch_nrdz_bijgw.toString(), wsch_nrdz_bijgw);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return meteoserver_zeeweerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testmqtt.proxies.Meteoserver_zeeweer that = (testmqtt.proxies.Meteoserver_zeeweer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestMqtt.Meteoserver_zeeweer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
